"""Add SystemSettings

Revision ID: 094cccbfc8ad
Revises: 37028895b997
Create Date: 2026-08-30 10:08:55.930280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094cccbfc8ad'
down_revision: Union[str, Sequence[str], None] = '37028895b997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_parking_spots', sa.Integer(), nullable=False),
    sa.Column('guest_parking_spots_offset', sa.Integer(), nullable=False),
    sa.Column('guest_parking_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_parking_post_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parking_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('spots_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parking_settings_pkey'))
    )
    op.drop_table('system_settings')
    # ### end Alembic commands ###
