"""added created_at to Users

Revision ID: 19d70e4df67d
Revises: 3bfb165858de
Create Date: 2026-02-17 14:31:35.383455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19d70e4df67d'
down_revision: Union[str, Sequence[str], None] = '3bfb165858de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cars_owner_id_fkey'), 'cars', type_='foreignkey')
    op.create_foreign_key('fk_cars_owner_id_users', 'cars', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('guest_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('guest_requests', 'visit_date')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('guest_requests', sa.Column('visit_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('guest_requests', 'updated_at')
    op.drop_constraint('fk_cars_owner_id_users', 'cars', type_='foreignkey')
    op.create_foreign_key(op.f('cars_owner_id_fkey'), 'cars', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
