"""Added agree on personal data processing to Users

Revision ID: 2adc033f4923
Revises: 7f31cc97e7d0
Create Date: 2026-02-14 21:07:41.463560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adc033f4923'
down_revision: Union[str, Sequence[str], None] = '7f31cc97e7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_agreed_processing_personal_data', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False, server_default='TRUE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'is_agreed_processing_personal_data')
    # ### end Alembic commands ###
