"""added completed_by to requests

Revision ID: 2d69ddab8915
Revises: bbe4afb9e7a1
Create Date: 2026-04-17 10:41:05.548152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d69ddab8915'
down_revision: Union[str, Sequence[str], None] = 'bbe4afb9e7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_requests', sa.Column('completed_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_guest_requests_completed_by_users', 'guest_requests', 'users', ['completed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_guest_requests_completed_by_users', 'guest_requests', type_='foreignkey')
    op.drop_column('guest_requests', 'completed_by')
    # ### end Alembic commands ###
