"""Add is_guest_parking_allowed to users

Revision ID: 37028895b997
Revises: b5b5c91f1a23
Create Date: 2026-08-06 09:15:23.080710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37028895b997'
down_revision: Union[str, Sequence[str], None] = 'b5b5c91f1a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_guest_parking_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_guest_parking_allowed')
    # ### end Alembic commands ###
