"""Updated Users table

Revision ID: 3bfb165858de
Revises: 2adc033f4923
Create Date: 2026-02-15 11:14:08.651218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfb165858de'
down_revision: Union[str, Sequence[str], None] = '2adc033f4923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_apartments_number_building_id', 'apartments', ['number', 'building_id'], unique=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'is_admin')
    op.drop_index('idx_apartments_number_building_id', table_name='apartments')
    # ### end Alembic commands ###
