"""Updated on cascade rules

Revision ID: 3c6c223ea05e
Revises: 19d70e4df67d
Create Date: 2026-02-17 15:30:57.375149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6c223ea05e'
down_revision: Union[str, Sequence[str], None] = '19d70e4df67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('guest_requests_user_id_fkey'), 'guest_requests', type_='foreignkey')
    op.create_foreign_key('fk_guest_requests_user_id_users', 'guest_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_guest_requests_user_id_users', 'guest_requests', type_='foreignkey')
    op.create_foreign_key(op.f('guest_requests_user_id_fkey'), 'guest_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
