"""added first_telegram_login_at column

Revision ID: 6d04bd7a4575
Revises: a8df9f8453af
Create Date: 2026-04-04 08:02:39.129556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d04bd7a4575'
down_revision: Union[str, Sequence[str], None] = 'a8df9f8453af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_telegram_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_telegram_login_at')
    # ### end Alembic commands ###
