"""added ondelete cascade for userlogs

Revision ID: 730600fe8b36
Revises: 987ae91d77d3
Create Date: 2026-05-22 21:27:59.263807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730600fe8b36'
down_revision: Union[str, Sequence[str], None] = '987ae91d77d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_activity_logs_user_id_fkey'), 'user_activity_logs', type_='foreignkey')
    op.create_foreign_key('user_activity_logs_user_id_fkey', 'user_activity_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_activity_logs_user_id_fkey', 'user_activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('user_activity_logs_user_id_fkey'), 'user_activity_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
