"""added has_rfid column to cars

Revision ID: 987ae91d77d3
Revises: 2d69ddab8915
Create Date: 2026-05-12 11:34:25.728574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987ae91d77d3'
down_revision: Union[str, Sequence[str], None] = '2d69ddab8915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('has_rfid', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'has_rfid')
    # ### end Alembic commands ###
