"""added is_resident_contact column

Revision ID: a9de7ec89a36
Revises: 3c6c223ea05e
Create Date: 2026-03-26 10:13:49.314535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9de7ec89a36'
down_revision: Union[str, Sequence[str], None] = '3c6c223ea05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_resident_contact', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_resident_contact')
    # ### end Alembic commands ###
