"""add guest parking and keyfob status

Revision ID: ab9406f7855f
Revises: 730600fe8b36
Create Date: 2026-07-25 08:45:33.420573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9406f7855f'
down_revision: Union[str, Sequence[str], None] = '730600fe8b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_parking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'keyfob_issued_entry', 'parked', 'keyfob_issued_exit', 'completed', 'expired', name='parkingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_parking_requests_id'), 'guest_parking_requests', ['id'], unique=False)
    op.create_index(op.f('ix_guest_parking_requests_license_plate'), 'guest_parking_requests', ['license_plate'], unique=False)
    op.create_index(op.f('ix_guest_parking_requests_status'), 'guest_parking_requests', ['status'], unique=False)
    op.create_table('keyfob_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('WITH_GUARD', 'WITH_GUEST', name='keyfobstate'), nullable=True),
    sa.Column('current_request_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_request_id'], ['guest_parking_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.execute("INSERT INTO keyfob_status (id, state) VALUES (1, 'WITH_GUARD')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyfob_status')
    op.drop_index(op.f('ix_guest_parking_requests_status'), table_name='guest_parking_requests')
    op.drop_index(op.f('ix_guest_parking_requests_license_plate'), table_name='guest_parking_requests')
    op.drop_index(op.f('ix_guest_parking_requests_id'), table_name='guest_parking_requests')
    op.drop_table('guest_parking_requests')
    # ### end Alembic commands ###
