"""added created_by updated_by fields

Revision ID: bbe4afb9e7a1
Revises: 3b9456b4b4d9
Create Date: 2026-04-12 10:55:00.070188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe4afb9e7a1'
down_revision: Union[str, Sequence[str], None] = '3b9456b4b4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_users_deleted_by_users', 'users', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_created_by_users', 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_updated_by_users', 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_updated_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_created_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_deleted_by_users', 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
